from typing import Dict, List, Optional, Text, Tuple, Union

ImageData = Union[str, bytes, Text]
SignatureTable = Dict[str, Tuple[int, Tuple[bytes, ...]]]

_UNSUPPORTED_IMAGE_SIGNATURES: SignatureTable

def _is_image_data(data: ImageData) -> Optional[str]: ...
def split_into_segments(data: bytes) -> List[bytes]: ...
def read_exif_from_file(filename: ImageData) -> Optional[bytes]: ...
def get_exif_seg(segments: List[bytes]) -> Optional[bytes]: ...
def merge_segments(segments: List[bytes], exif: Optional[bytes] = ...) -> bytes: ...
