from typing import List, Optional, Tuple

PNGChunk = Tuple[Optional[bytes], bytes]

def _chunks(data: bytes) -> List[PNGChunk]: ...
def _chunk(chunk_type: bytes, payload: bytes) -> bytes: ...
def get_exif(data: bytes) -> Optional[bytes]: ...
def insert(data: bytes, exif: bytes) -> bytes: ...
def remove(data: bytes) -> bytes: ...
