from typing import Dict, List, Optional, Tuple

WebPChunk = Dict[str, bytes]

def split(data: bytes) -> List[WebPChunk]: ...
def merge_chunks(chunks: List[WebPChunk]) -> bytes: ...
def _get_size_from_vp8x(chunk: WebPChunk) -> Tuple[int, int]: ...
def _get_size_from_vp8(chunk: WebPChunk) -> Optional[Tuple[int, int]]: ...
def _vp8L_contains_alpha(chunk_data: bytes) -> int: ...
def _get_size_from_vp8L(chunk: WebPChunk) -> Tuple[int, int]: ...
def _get_size_from_anmf(chunk: WebPChunk) -> Tuple[int, int]: ...
def set_vp8x(chunks: List[WebPChunk]) -> List[WebPChunk]: ...
def get_file_header(chunks: List[WebPChunk]) -> bytes: ...
def get_exif(data: bytes) -> Optional[bytes]: ...
def insert_exif_into_chunks(
    chunks: List[WebPChunk], exif_bytes: bytes
) -> List[WebPChunk]: ...
def insert(webp_bytes: bytes, exif_bytes: bytes) -> bytes: ...
def remove(webp_bytes: bytes) -> bytes: ...
